---
- name: Install Python utils on Debian OS Family
  apt: pkg={{ item.package }}
       update_cache=yes
       state=present
  with_items: logstash_python_utils
  when: ansible_os_family == "Debian"

- name: Install Java on Debian OS Family
  apt: pkg={{ apt_openjdk_java_package }}
       update_cache=yes
       state=present
  when: ansible_os_family == "Debian" and apt_install_openjdk_java

- name: Install Java on RedHat OS Family
  yum: name={{ open_jdk_rh }}
       state=latest
  when: ansible_os_family == "RedHat"
